apiVersion: v1
kind: Service
metadata:
  name: tax-api-svc
  labels:
    app: tax-api-app
spec:
  selector:
    app: tax-api-app
  ports:
    - name: tax-api
      protocol: TCP
      port: 8081
      targetPort: tax-api
